import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { gql, useMutation, useQuery } from '@apollo/client'
import { useState } from "react"

const ALL_RESOURCES = gql`
query GetAllResources {
  getAllResources {
    _id
    resources
    counter
  }
}
`
const UPDATE_RESOURCES = gql`
mutation UpdateResources($input: getResourcesInput) {
  updateResources(input: $input) {
    _id
    resources
    counter
  }
}
`

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data, error, loading } = useQuery(ALL_RESOURCES)
  const [updateCounter, { data: updateData, error: updateError, loading: updateLoading }] = useMutation(UPDATE_RESOURCES)

  async function myfoo() {
    for (let b = 0; b < 100; b++) {
      await updateCounter({
        variables: {
          input: {
            resources: "resources 1",
          }
        }
      })
    }
  }

  if (error || updateError) return <div>error</div>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main onClick={myfoo} className={styles.main}>
        {data ? data?.getAllResources.map((d) => {
          return <>isim:{d.resources} --- counter:{d.counter} <br /> </>
        }) : ""}
        <button onClick={myfoo}>Test </button>
      </main>
    </>
  )
}
